project:
  type: website
  output-dir: docs
  resources:
    - "eCRF.pdf"

website:
  title: "Ensaio GlucoCheck"
  navbar:
    background: "#1a5276"
    foreground: white
    left:
      - href: index.qmd
        text: Início
      - href: protocolos.qmd
        text: Protocolo
      - href: materiais.qmd
        text: Materiais
      - href: resultados.qmd
        text: Resultados
      - href: equipa.qmd
        text: Equipa
      - href: declaracaodeia.qmd
        text: Declaração IA

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: "Nesta página"