project:
  type: website
  output-dir: docs

website:
  title: "Ensaio GlucoCheck"
  navbar:
    background: "#1a5276"
    foreground: white
    left:
      - href: index.qmd
        text: Início
      - href: Protocolos.qmd
        text: Protocolo
      - href: Materiais.qmd
        text: Materiais
      - href: Resultados.qmd
        text: Resultados
      - href: Equipa.qmd
        text: Equipa

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-title: "Nesta página"